name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shopware-dal-toolkit-test
        ports:
          - 3306:3306

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.3' ]

    name: Tests P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: xdebug, dom, mbstring, zip, pdo_mysql

    - name: Get Composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: dependencies-php-${{ matrix.php }}-os-${{ matrix.os }}-version-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}
        restore-keys: dependencies-php-${{ matrix.php }}-os-${{ matrix.os }}-version-${{ matrix.dependency-version }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Recreate autoload file
      run: composer dump-autoload

    - name: Run Phpstan
      run: ./vendor/bin/phpstan

    - name: Run Unit Tests
      env:
        DATABASE_URL: mysql://root:root@mariadb/shopware-dal-toolkit-test
      run: XDEBUG_MODE=coverage vendor/bin/phpunit

    - name: Generate test coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.1
      with:
        coverage_badge_path: 'coverage-badge.svg'
        push_badge: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
